/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repairshop;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LabC
 */
public class VehicleForm extends javax.swing.JFrame {

        Connection con;
        Statement stmt;
        ResultSet rs;
        int curRow = 0;
        byte[] itemimage2;
    
    /**
     * Creates new form VehicleForm
     */
    public VehicleForm() {
        initComponents();
        DoConnect();
    }

    public void DoConnect(){
        try{
            String host = "jdbc:mysql://localhost:3306/VRS?zeroDateTimeBehavior=convertToNull";          
            String uName = "root";
            String uPass = "";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE );
            String sql = "SELECT * FROM Vehicle";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            byte[]imagedata=rs.getBytes("Image");
            ImageIcon format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(205, 129, Image.SCALE_DEFAULT));            
            itemImage.setIcon(format);
            int vehicle_col = rs.getInt("VehicleID");                      
            int customer_col = rs.getInt("CustomerID");                      
            String vehicle = Integer.toString(vehicle_col);
            String customer = Integer.toString(customer_col);            
            String plate = rs.getString("PlateNo");
            String manufacturer = rs.getString("Manufacturer");
            String model = rs.getString("Model");            
            
            txtVehicleID.setText(vehicle);           
            txtCustomerID.setText(customer);
            txtPlateNo.setText(plate);
            txtManufacturer.setText(manufacturer);           
            txtModel.setText(model);
            
      }
        catch (SQLException err){
            JOptionPane.showMessageDialog(VehicleForm.this, err.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("VRS?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        vehicleQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Vehicle v");
        vehicleList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : vehicleQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtVehicleID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPlateNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        itemImage = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNRecord = new javax.swing.JButton();
        btnURecord = new javax.swing.JButton();
        btnDRecord = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtVehicleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 202, 60, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehicle ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, -1, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Customer ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, -1, -1));
        jPanel2.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 253, 60, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Plate Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 284, -1, -1));
        jPanel2.add(txtPlateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 304, 170, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Manufacturer");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 335, -1, -1));
        jPanel2.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 406, 170, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Model");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 386, -1, -1));
        jPanel2.add(txtManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 355, 170, -1));

        itemImage.setBackground(new java.awt.Color(255, 255, 255));
        itemImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(itemImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 205, 129));

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/repairshop/Save.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 60, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/repairshop/Cancel.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLast.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel5.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, -1));

        btnFirst.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel5.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        btnNRecord.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        btnNRecord.setText("New Record");
        btnNRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNRecordActionPerformed(evt);
            }
        });
        jPanel5.add(btnNRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, -1));

        btnURecord.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        btnURecord.setText("Update Record");
        btnURecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnURecordActionPerformed(evt);
            }
        });
        jPanel5.add(btnURecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 110, -1));

        btnDRecord.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        btnDRecord.setText("Delete Record");
        btnDRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDRecordActionPerformed(evt);
            }
        });
        jPanel5.add(btnDRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/repairshop/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 65, -1));

        btnPrevious.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        btnNext.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel5.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 132, 510));

        jLabel6.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vehicle Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu jButton1 = new Menu();
        jButton1.setVisible(true);  
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try {
        if ( rs.next( ) ) {
             byte[]imagedata=rs.getBytes("Image");
            ImageIcon format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(205, 129, Image.SCALE_DEFAULT));            
            itemImage.setIcon(format);
            int vehicle_col = rs.getInt("VehicleID");                      
            int customer_col = rs.getInt("CustomerID");                      
            String vehicle = Integer.toString(vehicle_col);
            String customer = Integer.toString(customer_col);            
            String plate = rs.getString("PlateNo");
            String manufacturer = rs.getString("Manufacturer");
            String model = rs.getString("Model");            
            
            txtVehicleID.setText(vehicle);           
            txtCustomerID.setText(customer);
            txtPlateNo.setText(plate);
            txtManufacturer.setText(manufacturer);           
            txtModel.setText(model);
        }
        else {
        rs.previous( );
        JOptionPane.showMessageDialog(VehicleForm.this, "End of File");
        }
        }
        catch (SQLException err) {
        JOptionPane.showMessageDialog(VehicleForm.this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
      try {
        if ( rs.previous( ) ) {
            byte[]imagedata=rs.getBytes("Image");
            ImageIcon format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(205, 129, Image.SCALE_DEFAULT));            
            itemImage.setIcon(format);
            int vehicle_col = rs.getInt("VehicleID");                      
            int customer_col = rs.getInt("CustomerID");                      
            String vehicle = Integer.toString(vehicle_col);
            String customer = Integer.toString(customer_col);            
            String plate = rs.getString("PlateNo");
            String manufacturer = rs.getString("Manufacturer");
            String model = rs.getString("Model");            
            
            txtVehicleID.setText(vehicle);           
            txtCustomerID.setText(customer);
            txtPlateNo.setText(plate);
            txtManufacturer.setText(manufacturer);           
            txtModel.setText(model);            
            
        }
        else {
        rs.next( );
        JOptionPane.showMessageDialog(VehicleForm.this, "End of File");
        }
        }
        catch (SQLException err) {
        JOptionPane.showMessageDialog(VehicleForm.this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
       try{
            byte[]imagedata=rs.getBytes("Image");
            ImageIcon format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(205, 129, Image.SCALE_DEFAULT));            
            itemImage.setIcon(format);
            int vehicle_col = rs.getInt("VehicleID");                      
            int customer_col = rs.getInt("CustomerID");                      
            String vehicle = Integer.toString(vehicle_col);
            String customer = Integer.toString(customer_col);            
            String plate = rs.getString("PlateNo");
            String manufacturer = rs.getString("Manufacturer");
            String model = rs.getString("Model");            
            
            txtVehicleID.setText(vehicle);           
            txtCustomerID.setText(customer);
            txtPlateNo.setText(plate);
            txtManufacturer.setText(manufacturer);           
            txtModel.setText(model);
                        
       } 
      catch (SQLException err) {
        JOptionPane.showMessageDialog(VehicleForm.this, err.getMessage());
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        try{
            rs.last();
            byte[]imagedata=rs.getBytes("Image");
            ImageIcon format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(205, 129, Image.SCALE_DEFAULT));            
            itemImage.setIcon(format);
            int vehicle_col = rs.getInt("VehicleID");                      
            int customer_col = rs.getInt("CustomerID");                      
            String vehicle = Integer.toString(vehicle_col);
            String customer = Integer.toString(customer_col);            
            String plate = rs.getString("PlateNo");
            String manufacturer = rs.getString("Manufacturer");
            String model = rs.getString("Model");            
            
            txtVehicleID.setText(vehicle);           
            txtCustomerID.setText(customer);
            txtPlateNo.setText(plate);
            txtManufacturer.setText(manufacturer);           
            txtModel.setText(model);            
            
       } 
      catch (SQLException err) {
        JOptionPane.showMessageDialog(VehicleForm.this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnURecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnURecordActionPerformed
        // TODO add your handling code here:
        String vehicle = txtVehicleID.getText();
        String customer = txtCustomerID.getText();       
        String plate = txtPlateNo.getText();
        String manufacturer = txtManufacturer.getText();        
        String model = txtModel.getText();
        byte[] itemimage = itemimage2;
        
        int newVehicle = Integer.parseInt(vehicle);
        int newCustomer = Integer.parseInt(customer);      
        
        try{
            rs.updateInt("VehicleID", newVehicle);
            rs.updateInt("CustomerID", newCustomer);
            rs.updateString("PlateNo", plate);
            rs.updateString("Manufacturer", manufacturer);
            rs.updateString("Model", model);
            rs.updateBytes("Image", itemimage);
            rs.updateRow();
            JOptionPane.showMessageDialog(VehicleForm.this, "Database Updated");   
        }
        catch (SQLException err){
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnURecordActionPerformed

    private void btnNRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNRecordActionPerformed
        // TODO add your handling code here:
        try {
        rs.last();
        curRow = rs.getRow();              
        int curVehicle = curRow + 1;
        int curCustomer = curRow + 1;
        
        String newCurVehicleID = Integer.toString(curVehicle);
        String newCurCustomerID = Integer.toString(curCustomer);       
        byte[] imagedata = new byte[1024];
        ImageIcon format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(205, 129, Image.SCALE_DEFAULT));
        
        itemImage.setIcon(format);
        txtVehicleID.setText(newCurVehicleID);       
        txtCustomerID.setText(newCurCustomerID);
        txtPlateNo.setText("");        
        txtManufacturer.setText("");
        txtModel.setText("");        
        
        btnFirst.setEnabled( false );
        btnPrevious.setEnabled( false ) ;
        btnNext.setEnabled( false );
        btnLast.setEnabled( false );
        btnURecord.setEnabled( false );
        btnDRecord.setEnabled( false );
        btnNRecord.setEnabled( false );

        btnSave.setEnabled( true );
        btnCancel.setEnabled( true );
        }
        catch (SQLException err){
             System.out.println(err.getMessage());
             }
    }//GEN-LAST:event_btnNRecordActionPerformed

    private void btnDRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDRecordActionPerformed
        // TODO add your handling code here:
        try{
          rs.deleteRow();
          JOptionPane.showMessageDialog(VehicleForm.this, "Record Deleted!");
          DoConnect();
          
        }
         catch (SQLException err){
             System.out.println(err.getMessage());
             }
    }//GEN-LAST:event_btnDRecordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        try {
        rs.first();      
        txtVehicleID.setText(rs.getString("VehicleID"));       
        txtCustomerID.setText(rs.getString("CustomerID"));
        txtPlateNo.setText(rs.getString("PlateNo"));              
        txtManufacturer.setText(rs.getString("Manufacturer"));       
        txtModel.setText(rs.getString("Model"));       
            
        btnFirst.setEnabled( true );
        btnPrevious.setEnabled( true ) ;
        btnNext.setEnabled( true );
        btnLast.setEnabled( true );
        btnURecord.setEnabled( true );
        btnDRecord.setEnabled( true );
        btnNRecord.setEnabled( true );

        btnSave.setEnabled( false );
        btnCancel.setEnabled( false );
        }
        catch (SQLException err){
             System.out.println(err.getMessage());
             }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            String vehicle = txtVehicleID.getText();
            String customer = txtCustomerID.getText();         
            String plate = txtPlateNo.getText();
            String manufacturer = txtManufacturer.getText();
            String model = txtModel.getText();
            
            byte[] itemimage = itemimage2;
        
            int newVehicle = Integer.parseInt(vehicle);   
            int newCustomer = Integer.parseInt(customer);
            
            
            try{
            rs.moveToInsertRow();
                
            rs.updateInt("VehicleID", newVehicle);
            rs.updateInt("CustomerID", newCustomer);            
            rs.updateString("PlateNo", plate);      
            rs.updateString("Manufacturer", manufacturer);
            rs.updateString("Model", model);            
            rs.updateBytes("Image", itemimage);
                
            rs.insertRow();
                
            stmt.close();
            rs.close();
                
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE );
            String sql = "SELECT * FROM customer";
            rs = stmt.executeQuery(sql);
            
            rs.next();            
            
            txtVehicleID.setText(vehicle);          
            txtCustomerID.setText(customer);          
            txtPlateNo.setText(plate);            
            txtManufacturer.setText(manufacturer);
            txtModel.setText(model);                       
                                            
            btnFirst.setEnabled( true );
            btnPrevious.setEnabled( true ) ;
            btnNext.setEnabled( true );
            btnLast.setEnabled( true );
            btnURecord.setEnabled( true );
            btnDRecord.setEnabled( true );
            btnNRecord.setEnabled( true );

            btnSave.setEnabled( false );
            btnCancel.setEnabled( false );
            
            JOptionPane.showMessageDialog(VehicleForm.this, "Database Saved!");
            DoConnect();
      }
        catch (SQLException err){
            JOptionPane.showMessageDialog(VehicleForm.this, err.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
       JFileChooser ch = new JFileChooser();      
       ch.showOpenDialog(null);
       FileFilter imageFilter = new FileNameExtensionFilter(
       "Image files", ImageIO.getReaderFileSuffixes());
       ch.setFileFilter(imageFilter);
       File f= ch.getSelectedFile();
       String filename = f.getAbsolutePath();
       
       try{
           File image= new File(filename);           
           FileInputStream fs=new FileInputStream(image);
           ByteArrayOutputStream bos= new ByteArrayOutputStream();
           byte[] buf= new byte [1024];
           for(int readNum;(readNum = fs.read(buf))!=-1;){
                bos.write(buf,0,readNum);                
                }
           byte[] item_image = bos.toByteArray();
           itemimage2 = item_image;
           
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(VehicleForm.this, e.getMessage());
       }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new VehicleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDRecord;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNRecord;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnURecord;
    private javax.swing.JButton btnUpload;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel itemImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlateNo;
    private javax.swing.JTextField txtVehicleID;
    private java.util.List<repairshop.Vehicle> vehicleList;
    private javax.persistence.Query vehicleQuery;
    // End of variables declaration//GEN-END:variables
}
